// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v3.21.12
// source: vibecms_plugin.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ExtensionPlugin_GetSubscriptions_FullMethodName  = "/vibecmsplugin.ExtensionPlugin/GetSubscriptions"
	ExtensionPlugin_HandleEvent_FullMethodName       = "/vibecmsplugin.ExtensionPlugin/HandleEvent"
	ExtensionPlugin_Shutdown_FullMethodName          = "/vibecmsplugin.ExtensionPlugin/Shutdown"
	ExtensionPlugin_Initialize_FullMethodName        = "/vibecmsplugin.ExtensionPlugin/Initialize"
	ExtensionPlugin_HandleHTTPRequest_FullMethodName = "/vibecmsplugin.ExtensionPlugin/HandleHTTPRequest"
)

// ExtensionPluginClient is the client API for ExtensionPlugin service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ExtensionPluginClient interface {
	// GetSubscriptions returns the list of events this plugin wants to handle.
	GetSubscriptions(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*SubscriptionList, error)
	// HandleEvent is called when a subscribed event fires.
	HandleEvent(ctx context.Context, in *EventRequest, opts ...grpc.CallOption) (*EventResponse, error)
	// Shutdown tells the plugin to clean up and exit gracefully.
	Shutdown(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Empty, error)
	// Initialize passes the host service broker ID so the plugin can call back.
	Initialize(ctx context.Context, in *InitializeRequest, opts ...grpc.CallOption) (*Empty, error)
	// HandleHTTPRequest proxies an admin API request to the plugin.
	HandleHTTPRequest(ctx context.Context, in *PluginHTTPRequest, opts ...grpc.CallOption) (*PluginHTTPResponse, error)
}

type extensionPluginClient struct {
	cc grpc.ClientConnInterface
}

func NewExtensionPluginClient(cc grpc.ClientConnInterface) ExtensionPluginClient {
	return &extensionPluginClient{cc}
}

func (c *extensionPluginClient) GetSubscriptions(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*SubscriptionList, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SubscriptionList)
	err := c.cc.Invoke(ctx, ExtensionPlugin_GetSubscriptions_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *extensionPluginClient) HandleEvent(ctx context.Context, in *EventRequest, opts ...grpc.CallOption) (*EventResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EventResponse)
	err := c.cc.Invoke(ctx, ExtensionPlugin_HandleEvent_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *extensionPluginClient) Shutdown(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, ExtensionPlugin_Shutdown_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *extensionPluginClient) Initialize(ctx context.Context, in *InitializeRequest, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, ExtensionPlugin_Initialize_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *extensionPluginClient) HandleHTTPRequest(ctx context.Context, in *PluginHTTPRequest, opts ...grpc.CallOption) (*PluginHTTPResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PluginHTTPResponse)
	err := c.cc.Invoke(ctx, ExtensionPlugin_HandleHTTPRequest_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ExtensionPluginServer is the server API for ExtensionPlugin service.
// All implementations must embed UnimplementedExtensionPluginServer
// for forward compatibility.
type ExtensionPluginServer interface {
	// GetSubscriptions returns the list of events this plugin wants to handle.
	GetSubscriptions(context.Context, *Empty) (*SubscriptionList, error)
	// HandleEvent is called when a subscribed event fires.
	HandleEvent(context.Context, *EventRequest) (*EventResponse, error)
	// Shutdown tells the plugin to clean up and exit gracefully.
	Shutdown(context.Context, *Empty) (*Empty, error)
	// Initialize passes the host service broker ID so the plugin can call back.
	Initialize(context.Context, *InitializeRequest) (*Empty, error)
	// HandleHTTPRequest proxies an admin API request to the plugin.
	HandleHTTPRequest(context.Context, *PluginHTTPRequest) (*PluginHTTPResponse, error)
	mustEmbedUnimplementedExtensionPluginServer()
}

// UnimplementedExtensionPluginServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedExtensionPluginServer struct{}

func (UnimplementedExtensionPluginServer) GetSubscriptions(context.Context, *Empty) (*SubscriptionList, error) {
	return nil, status.Error(codes.Unimplemented, "method GetSubscriptions not implemented")
}
func (UnimplementedExtensionPluginServer) HandleEvent(context.Context, *EventRequest) (*EventResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method HandleEvent not implemented")
}
func (UnimplementedExtensionPluginServer) Shutdown(context.Context, *Empty) (*Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method Shutdown not implemented")
}
func (UnimplementedExtensionPluginServer) Initialize(context.Context, *InitializeRequest) (*Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method Initialize not implemented")
}
func (UnimplementedExtensionPluginServer) HandleHTTPRequest(context.Context, *PluginHTTPRequest) (*PluginHTTPResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method HandleHTTPRequest not implemented")
}
func (UnimplementedExtensionPluginServer) mustEmbedUnimplementedExtensionPluginServer() {}
func (UnimplementedExtensionPluginServer) testEmbeddedByValue()                         {}

// UnsafeExtensionPluginServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ExtensionPluginServer will
// result in compilation errors.
type UnsafeExtensionPluginServer interface {
	mustEmbedUnimplementedExtensionPluginServer()
}

func RegisterExtensionPluginServer(s grpc.ServiceRegistrar, srv ExtensionPluginServer) {
	// If the following call panics, it indicates UnimplementedExtensionPluginServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ExtensionPlugin_ServiceDesc, srv)
}

func _ExtensionPlugin_GetSubscriptions_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ExtensionPluginServer).GetSubscriptions(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ExtensionPlugin_GetSubscriptions_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ExtensionPluginServer).GetSubscriptions(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _ExtensionPlugin_HandleEvent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EventRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ExtensionPluginServer).HandleEvent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ExtensionPlugin_HandleEvent_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ExtensionPluginServer).HandleEvent(ctx, req.(*EventRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ExtensionPlugin_Shutdown_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ExtensionPluginServer).Shutdown(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ExtensionPlugin_Shutdown_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ExtensionPluginServer).Shutdown(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _ExtensionPlugin_Initialize_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InitializeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ExtensionPluginServer).Initialize(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ExtensionPlugin_Initialize_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ExtensionPluginServer).Initialize(ctx, req.(*InitializeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ExtensionPlugin_HandleHTTPRequest_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PluginHTTPRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ExtensionPluginServer).HandleHTTPRequest(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ExtensionPlugin_HandleHTTPRequest_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ExtensionPluginServer).HandleHTTPRequest(ctx, req.(*PluginHTTPRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ExtensionPlugin_ServiceDesc is the grpc.ServiceDesc for ExtensionPlugin service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ExtensionPlugin_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "vibecmsplugin.ExtensionPlugin",
	HandlerType: (*ExtensionPluginServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetSubscriptions",
			Handler:    _ExtensionPlugin_GetSubscriptions_Handler,
		},
		{
			MethodName: "HandleEvent",
			Handler:    _ExtensionPlugin_HandleEvent_Handler,
		},
		{
			MethodName: "Shutdown",
			Handler:    _ExtensionPlugin_Shutdown_Handler,
		},
		{
			MethodName: "Initialize",
			Handler:    _ExtensionPlugin_Initialize_Handler,
		},
		{
			MethodName: "HandleHTTPRequest",
			Handler:    _ExtensionPlugin_HandleHTTPRequest_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "vibecms_plugin.proto",
}
