package main

import (
	"encoding/json"
	"strings"
	"testing"

	"vibecms/internal/coreapi"
	pb "vibecms/pkg/plugin/proto"
)

func seedFormWithNotifConfig(h *FakeHost) {
	h.DataCreate(ctx(), formsTable, map[string]any{
		"name": "Notif Form",
		"slug": "notif-form",
		"fields": `[
			{"id":"email","label":"Email","type":"email"},
			{"id":"message","label":"Message","type":"textarea"}
		]`,
		"layout":   `<form></form>`,
		"settings": `{}`,
		"notifications": `[
			{
				"enabled": true,
				"to": "admin@example.com",
				"subject": "Test from {{.FormName}}",
				"body": "<p>{{.Field.message}}</p>"
			}
		]`,
	})
}

// ---- handleNotificationTest ----

func TestHandleNotificationTest_Success(t *testing.T) {
	h := NewFakeHost()
	p := newPlugin(h)
	seedFormWithNotifConfig(h)

	body, _ := json.Marshal(map[string]any{
		"override_recipient": "tester@example.com",
		"sample_data":        map[string]any{"email": "test@example.com", "message": "Hello"},
	})
	req := &pb.PluginHTTPRequest{
		Method: "POST",
		Path:   "1/notifications/0/test",
		Body:   body,
	}
	resp, err := p.handleNotificationTest(ctx(), 1, 0, req)
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
	if resp.StatusCode != 200 {
		t.Errorf("expected 200, got %d (body: %s)", resp.StatusCode, resp.Body)
	}
	if len(h.Sent) != 1 {
		t.Fatalf("expected 1 email, got %d", len(h.Sent))
	}
	if h.Sent[0].To[0] != "tester@example.com" {
		t.Errorf("to: got %v", h.Sent[0].To)
	}
	// Subject should have [Test] prefix
	if !strings.HasPrefix(h.Sent[0].Subject, "[Test]") {
		t.Errorf("subject should have [Test] prefix, got %q", h.Sent[0].Subject)
	}
}

func TestHandleNotificationTest_AutoGeneratedSampleData(t *testing.T) {
	h := NewFakeHost()
	p := newPlugin(h)
	seedFormWithNotifConfig(h)

	// No sample_data — should auto-generate from field types
	body, _ := json.Marshal(map[string]any{
		"override_recipient": "tester@example.com",
	})
	req := &pb.PluginHTTPRequest{
		Method: "POST",
		Path:   "1/notifications/0/test",
		Body:   body,
	}
	resp, err := p.handleNotificationTest(ctx(), 1, 0, req)
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
	if resp.StatusCode != 200 {
		t.Errorf("expected 200, got %d (body: %s)", resp.StatusCode, resp.Body)
	}
	if len(h.Sent) != 1 {
		t.Fatalf("expected 1 email, got %d", len(h.Sent))
	}
}

func TestHandleNotificationTest_FormNotFound(t *testing.T) {
	h := NewFakeHost()
	p := newPlugin(h)

	body, _ := json.Marshal(map[string]any{"override_recipient": "x@example.com"})
	req := &pb.PluginHTTPRequest{Method: "POST", Body: body}
	resp, err := p.handleNotificationTest(ctx(), 999, 0, req)
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
	if resp.StatusCode != 404 {
		t.Errorf("expected 404, got %d", resp.StatusCode)
	}
}

func TestHandleNotificationTest_InvalidIndex(t *testing.T) {
	h := NewFakeHost()
	p := newPlugin(h)
	seedFormWithNotifConfig(h)

	body, _ := json.Marshal(map[string]any{"override_recipient": "x@example.com"})
	req := &pb.PluginHTTPRequest{Method: "POST", Body: body}
	// Index 99 is out of range
	resp, err := p.handleNotificationTest(ctx(), 1, 99, req)
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
	if resp.StatusCode != 400 {
		t.Errorf("expected 400, got %d", resp.StatusCode)
	}
}

func TestHandleNotificationTest_NoRecipient(t *testing.T) {
	h := NewFakeHost()
	p := newPlugin(h)

	// Form with no recipients in notification
	h.DataCreate(ctx(), formsTable, map[string]any{
		"name": "Test",
		"slug": "test",
		"notifications": `[{
			"enabled": true,
			"to": "",
			"subject": "Sub",
			"body": "Body"
		}]`,
		"fields":   `[]`,
		"settings": `{}`,
	})

	req := &pb.PluginHTTPRequest{Method: "POST", Body: []byte(`{}`)}
	resp, err := p.handleNotificationTest(ctx(), 1, 0, req)
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
	if resp.StatusCode != 400 {
		t.Errorf("expected 400 (no recipient), got %d (body: %s)", resp.StatusCode, resp.Body)
	}
}

func TestHandleNotificationTest_InvalidEmail(t *testing.T) {
	h := NewFakeHost()
	p := newPlugin(h)
	seedFormWithNotifConfig(h)

	body, _ := json.Marshal(map[string]any{"override_recipient": "not-valid-email"})
	req := &pb.PluginHTTPRequest{Method: "POST", Body: body}
	resp, err := p.handleNotificationTest(ctx(), 1, 0, req)
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
	if resp.StatusCode != 400 {
		t.Errorf("expected 400 (invalid email), got %d", resp.StatusCode)
	}
}

func TestHandleNotificationTest_FallbackToUserEmail(t *testing.T) {
	h := NewFakeHost()
	p := newPlugin(h)
	// Form notification with template recipient (has {{}}) so override is needed
	h.DataCreate(ctx(), formsTable, map[string]any{
		"name":     "Test",
		"slug":     "test",
		"fields":   `[]`,
		"settings": `{}`,
		"notifications": `[{
			"enabled": true,
			"to": "{{.Field.email}}",
			"subject": "Sub",
			"body": "Body"
		}]`,
	})
	// Set up user stub
	h.UserStub[42] = &coreapi.User{ID: 42, Email: "user@example.com", Name: "Test User"}

	req := &pb.PluginHTTPRequest{
		Method: "POST",
		Body:   []byte(`{}`),
		UserId: 42,
	}
	resp, err := p.handleNotificationTest(ctx(), 1, 0, req)
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
	if resp.StatusCode != 200 {
		t.Errorf("expected 200, got %d (body: %s)", resp.StatusCode, resp.Body)
	}
	if len(h.Sent) == 0 || h.Sent[0].To[0] != "user@example.com" {
		t.Errorf("expected email sent to user@example.com, got %v", h.Sent)
	}
}

func TestHandleNotificationTest_DefaultBodyWhenNoBodyTemplate(t *testing.T) {
	h := NewFakeHost()
	p := newPlugin(h)

	h.DataCreate(ctx(), formsTable, map[string]any{
		"name":     "Test",
		"slug":     "test",
		"fields":   `[{"id":"name","label":"Name","type":"text"}]`,
		"settings": `{}`,
		"notifications": `[{
			"enabled": true,
			"to": "admin@example.com",
			"subject": "Sub"
		}]`,
	})

	body, _ := json.Marshal(map[string]any{"override_recipient": "admin@example.com"})
	req := &pb.PluginHTTPRequest{Method: "POST", Body: body}
	resp, err := p.handleNotificationTest(ctx(), 1, 0, req)
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
	if resp.StatusCode != 200 {
		t.Errorf("expected 200, got %d", resp.StatusCode)
	}
	if len(h.Sent) > 0 && !strings.Contains(h.Sent[0].HTML, "<table") {
		t.Error("default body should be an HTML table")
	}
}
